# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actives', '0058_maindeposits_mainloans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActivesLoans',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('insurance', models.BooleanField(blank=True, default=False)),
                ('insurance_sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('remainder', models.FloatField(blank=True, default=0.0, null=True)),
                ('sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('loan_term', models.BigIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('month_payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('maintenance_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical loan',
                'verbose_name_plural': 'historical loans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ActivesLoans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('insurance', models.BooleanField(blank=True, default=False)),
                ('insurance_sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('remainder', models.FloatField(blank=True, default=0.0, null=True)),
                ('sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('loan_term', models.BigIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('month_payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('maintenance_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_images/')),
                ('expenses', models.ManyToManyField(blank=True, null=True, related_name='+', to='actives.activesexpenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ActivesDeposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
