# Generated by Django 4.1.7 on 2024-02-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0060_remove_historicalproperty_rent_type_and_more'),
        ('actives_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesdeposit',
            name='incomes',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='actives.activesincome'),
        ),
    ]
