# Generated by Django 4.1.7 on 2024-02-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0062_rename_owner_historicaltransport_owner_count_and_more'),
        ('actives_deposit', '0004_alter_activesdeposit_user_alter_activesloans_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalactivesloans',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalactivesloans',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivesLoans',
        ),
        migrations.DeleteModel(
            name='HistoricalActivesLoans',
        ),
    ]
