# Generated by Django 4.1.6 on 2023-05-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='month_income',
        ),
    ]
