# Generated by Django 4.1.6 on 2023-05-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passives', '0002_remove_property_month_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loans',
            name='insurance',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='insurance_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='maintenance_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='month_payment',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loans',
            name='percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='remainder',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='sum',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='passives',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='passives',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='passives',
            name='transports',
        ),
        migrations.AlterField(
            model_name='property',
            name='actual_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_consumption',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bought_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='equipment_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='initial_payment',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='loan_term',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_expense',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_payment',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_type',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='average_consumption',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bought_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='initial_payment',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='loan_term',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='month_expense',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='month_payment',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='owner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='owner_type',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='use',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='passives',
            name='loans',
            field=models.ManyToManyField(blank=True, to='passives.loans'),
        ),
        migrations.AddField(
            model_name='passives',
            name='properties',
            field=models.ManyToManyField(blank=True, to='passives.property'),
        ),
        migrations.AddField(
            model_name='passives',
            name='transports',
            field=models.ManyToManyField(blank=True, to='passives.transport'),
        ),
    ]
