# Generated by Django 4.1.6 on 2023-05-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0003_alter_loans_data_alter_loans_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='insurance_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
