# Generated by Django 4.1.6 on 2023-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0005_loans_created_at_alter_loans_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='loan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='loan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='initial_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='loan_term',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='initial_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='loan_term',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='month_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
