# Generated by Django 4.1.6 on 2023-07-06 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0006_property_loan_transport_loan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('done', models.BooleanField(default=0, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passives.property')),
            ],
            options={
                'verbose_name': 'property_asset',
                'verbose_name_plural': 'property_asset',
                'ordering': ('id',),
            },
        ),
    ]
