# Generated by Django 4.1.6 on 2023-07-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0007_propertyasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='average_market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='max_market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='min_market_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
