# Generated by Django 4.1.6 on 2023-07-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0008_transport_average_market_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='mark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='model',
            field=models.TextField(blank=True),
        ),
    ]
