# Generated by Django 4.1.6 on 2023-07-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0009_transport_mark_transport_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='average_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='month_expense',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
