# Generated by Django 4.1.6 on 2023-07-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0011_property_created_at_propertyasset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransport',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='brand',
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='actual_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='average_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='bought_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='equipment_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='month_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='rent_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpropertyasset',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpropertyasset',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='owner_type',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='actual_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bought_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='equipment_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyasset',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyasset',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='owner_type',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
