# Generated by Django 4.1.6 on 2023-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0012_remove_historicaltransport_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransport',
            name='bought_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='mark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bought_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
