# Generated by Django 4.1.6 on 2023-07-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0013_alter_historicaltransport_bought_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='name',
        ),
    ]
