# Generated by Django 4.1.6 on 2023-07-25 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passives', '0014_remove_historicaltransport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloans',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_images/'),
        ),
        migrations.AddField(
            model_name='passives',
            name='total_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passives',
            name='total_funds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passives',
            name='loans',
            field=models.ManyToManyField(blank=True, null=True, to='passives.loans'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, to='passives.property'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='transports',
            field=models.ManyToManyField(blank=True, null=True, to='passives.transport'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passives_transport_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='passives.transport')),
            ],
            options={
                'verbose_name': 'transport-image',
                'verbose_name_plural': 'transport-image',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passives.property')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passives.transport')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='passives.transportimage'),
        ),
    ]
