# Generated by Django 4.1.6 on 2023-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0015_historicalloans_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passives',
            name='properties',
            field=models.ManyToManyField(blank=True, to='passives.property'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='transports',
            field=models.ManyToManyField(blank=True, to='passives.transport'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.transportimage'),
        ),
    ]
