# Generated by Django 4.1.6 on 2023-07-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0016_alter_passives_properties_alter_passives_transports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloans',
            name='image',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loans',
            name='image',
            field=models.ImageField(blank=True, upload_to='bank_images/'),
        ),
    ]
