# Generated by Django 4.1.6 on 2023-07-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0018_expenses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passives',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.expenses'),
        ),
        migrations.AddField(
            model_name='transport',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.expenses'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='passives.property'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='passives.transport'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='loans',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.loans'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.property'),
        ),
        migrations.AlterField(
            model_name='passives',
            name='transports',
            field=models.ManyToManyField(blank=True, related_name='+', to='passives.transport'),
        ),
    ]
