# Generated by Django 4.1.6 on 2023-07-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0019_rename_user_id_passives_user_property_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalloans',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='user_id',
            new_name='user',
        ),
    ]
