# Generated by Django 4.1.7 on 2023-08-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0024_alter_passives_loans_alter_passives_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passives',
            name='loans',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passives.mainloans'),
        ),
    ]
