# Generated by Django 4.1.7 on 2023-08-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0025_alter_passives_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='passives.loans'),
        ),
        migrations.AddField(
            model_name='loans',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='passives.expenses'),
        ),
    ]
