# Generated by Django 4.1.7 on 2023-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0027_alter_passives_loans_alter_passives_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloans',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
