# Generated by Django 4.1.7 on 2023-08-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0028_historicalloans_total_expense_loans_total_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproperty',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='user',
        ),
    ]
