# Generated by Django 4.1.7 on 2023-08-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0029_rename_user_id_historicalproperty_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='user_id',
            new_name='user',
        ),
    ]
