# Generated by Django 4.1.7 on 2023-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0032_historicalproperty_equipment_property_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
