# Generated by Django 4.1.7 on 2023-08-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0018_rename_total_expenses_card_total_expense_and_more'),
        ('passives', '0034_expenses_description_expenses_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='balance.card'),
        ),
    ]
