# Generated by Django 4.1.7 on 2024-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0037_remove_historicalproperty_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
    ]
