# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0039_expenses_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalloans',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='data',
            new_name='date',
        ),
    ]
