# Generated by Django 4.1.7 on 2024-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0040_rename_data_historicalloans_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloans',
            name='is_borrowed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='rent_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='is_borrowed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='rent_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
