# Generated by Django 4.1.7 on 2024-02-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passives', '0041_historicalloans_is_borrowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBorrows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_expenses', models.FloatField(blank=True, default=0.0, null=True)),
                ('borrows', models.ManyToManyField(blank=True, to='passives.loans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='passives',
            name='borrows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passives.mainborrows'),
        ),
    ]
