# Generated by Django 4.1.7 on 2024-03-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0043_historicalloans_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloans',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
