# Generated by Django 4.1.7 on 2024-03-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0044_alter_historicalloans_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloans',
            name='is_card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='is_card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
