# Generated by Django 4.1.7 on 2023-11-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('retail_place_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_number', models.PositiveIntegerField(blank=True, null=True)),
                ('taxation_type', models.PositiveIntegerField(blank=True, null=True)),
                ('electronic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiscal_sign', models.PositiveIntegerField(blank=True, null=True)),
                ('request_number', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_document_number', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_document_format_version', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipt_scanner.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
            },
        ),
    ]
