# Generated by Django 4.1.7 on 2023-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_scanner', '0002_receipt_fiscal_drive_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='taxation_type',
            new_name='applied_taxation_type',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='electronic_amount',
            new_name='cash_total_sum',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='total_amount',
            new_name='nds_18',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='item_number',
        ),
        migrations.AddField(
            model_name='receipt',
            name='credit_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ecash_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='retail_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fiscal_sign',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user_inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
