# Generated by Django 4.1.6 on 2023-07-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_alter_balance_user'),
        ('front', '0007_alter_customuser_all_actives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='balance.balance'),
        ),
    ]
