# Generated by Django 4.1.7 on 2023-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_temporarycustomuser_remove_userprofile_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
