# Generated by Django 4.1.7 on 2023-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_rename_first_name_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycustomuser',
            name='password',
            field=models.BigIntegerField(null=True),
        ),
    ]
