# Generated by Django 4.1.7 on 2023-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_temporarycustomuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
