# Generated by Django 4.1.7 on 2023-10-05 08:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_alter_temporarycustomuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
