# Generated by Django 4.1.7 on 2023-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_alter_temporarycustomuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
