# Generated by Django 4.1.7 on 2023-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
