# Generated by Django 4.1.7 on 2023-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
