# Generated by Django 4.1.7 on 2023-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
