# Generated by Django 4.1.7 on 2023-10-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='email',
        ),
    ]
