# Generated by Django 4.1.7 on 2023-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycustomuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarycustomuser',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
