# Generated by Django 4.1.7 on 2023-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_temporarycustomuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='password',
            field=models.BinaryField(null=True),
        ),
    ]
