# Generated by Django 4.1.7 on 2023-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_alter_temporarycustomuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycustomuser',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
