# Generated by Django 4.1.7 on 2023-10-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0024_alter_temporarycustomuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='temporarycustomuser',
            name='updated_at',
        ),
    ]
