# Generated by Django 4.1.7 on 2023-12-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0020_alter_balance_card_list'),
        ('todo', '0034_alter_historicaltodotask_color_alter_todotask_color'),
        ('income_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workincome',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.card'),
        ),
        migrations.AlterField(
            model_name='workincome',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todo.project'),
        ),
    ]
