# Generated by Django 4.1.7 on 2024-01-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0024_alter_expenses_content_type_alter_expenses_object_id'),
        ('income_expenses', '0002_workincome_writeoff_account_alter_workincome_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='workincome',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='balance.income'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
