# Generated by Django 4.1.6 on 2023-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funds_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('write_off_account', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='todotask',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='todo.todoitem'),
        ),
    ]
