# Generated by Django 4.1.6 on 2023-05-23 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_project_name_project_user_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='todotask',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todotask',
            old_name='items',
            new_name='desc_list',
        ),
        migrations.RenameField(
            model_name='todotask',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='funds_spent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reserved_funds',
        ),
        migrations.RemoveField(
            model_name='project',
            name='write_off_account',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotask',
            name='done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotask',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotask',
            name='expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todotask'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.TextField(),
        ),
    ]
