# Generated by Django 4.1.6 on 2023-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_end_date_project_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
