# Generated by Django 4.1.6 on 2023-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_project_date_end_alter_project_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
