# Generated by Django 4.1.6 on 2023-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todotask_date_alter_todotask_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
