# Generated by Django 4.1.6 on 2023-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_todotask_endtime_alter_todotask_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='desc_list',
            field=models.ManyToManyField(blank=True, related_name='items', to='todo.todoitem'),
        ),
    ]
