# Generated by Django 4.1.6 on 2023-05-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0011_alter_todotask_desclist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='planned_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reserved_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spent_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='writeoff_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projects', models.ManyToManyField(to='todo.project')),
                ('tasks', models.ManyToManyField(to='todo.todotask')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
