# Generated by Django 4.1.6 on 2023-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_todotask_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
