# Generated by Django 4.1.6 on 2023-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_project_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
