# Generated by Django 4.1.6 on 2023-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_project_created_at_project_task_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_list',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_list',
            field=models.ManyToManyField(related_name='+', to='todo.todotask'),
        ),
    ]
