# Generated by Django 4.1.6 on 2023-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_rename_project_id_todotask_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks_list',
            field=models.ManyToManyField(blank=True, related_name='+', to='todo.todotask'),
        ),
    ]
