# Generated by Django 4.1.6 on 2023-07-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_balance_created_at_card_created_at_and_more'),
        ('todo', '0023_historicaltodotask_historicaltodoitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='balance.card'),
        ),
        migrations.AlterField(
            model_name='project',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.card'),
        ),
    ]
