# Generated by Django 4.1.7 on 2023-08-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_historicalproject_total_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltodotask',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='expense',
        ),
    ]
