# Generated by Django 4.1.7 on 2023-08-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_remove_historicaltodotask_expense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicaltodotask',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todotask',
            old_name='user_id',
            new_name='user',
        ),
    ]
