# Generated by Django 4.1.7 on 2023-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_rename_user_id_historicalproject_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
