# Generated by Django 4.1.7 on 2023-08-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_expenses_writeoff_account_income_writeoff_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
