# Generated by Django 4.1.7 on 2023-10-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0019_balance_favourite_cards'),
        ('todo', '0031_expenses_description_expenses_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltodotask',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='balance.card'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.card'),
        ),
    ]
