# Generated by Django 4.1.7 on 2023-11-02 00:56

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_historicaltodotask_writeoff_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltodotask',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
