# Generated by Django 4.1.7 on 2023-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0033_historicaltodotask_color_todotask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltodotask',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
