# Generated by Django 4.1.7 on 2024-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_alter_historicaltodotask_color_alter_todotask_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
