# Generated by Django 4.1.7 on 2024-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_income_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
    ]
