# Generated by Django 4.1.6 on 2023-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('id',), 'verbose_name': 'balance', 'verbose_name_plural': 'balance'},
        ),
        migrations.AddField(
            model_name='balance',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
