# Generated by Django 4.1.6 on 2023-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_options_balance_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='balance',
            new_name='remainder',
        ),
        migrations.AddField(
            model_name='balance',
            name='card_list',
            field=models.ManyToManyField(blank=True, to='balance.card'),
        ),
    ]
