# Generated by Django 4.1.6 on 2023-07-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_balance_created_at_card_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='total_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='balance.card')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='balance.card')),
            ],
        ),
    ]
