# Generated by Django 4.1.6 on 2023-07-30 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0005_balance_total_expenses_balance_total_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='card',
            name='income',
        ),
        migrations.RemoveField(
            model_name='historicalcard',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='historicalcard',
            name='income',
        ),
        migrations.AddField(
            model_name='card',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='balance.expenses'),
        ),
        migrations.AddField(
            model_name='card',
            name='incomes',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='balance.income'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
