# Generated by Django 4.1.6 on 2023-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_remove_card_expense_remove_card_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='balance.expenses'),
        ),
        migrations.AlterField(
            model_name='card',
            name='incomes',
            field=models.ManyToManyField(blank=True, related_name='+', to='balance.income'),
        ),
    ]
