# Generated by Django 4.1.7 on 2023-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0011_balance_card_income_historicalbalance_card_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='incomes',
            new_name='income',
        ),
    ]
