# Generated by Django 4.1.7 on 2023-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0015_expenses_description_expenses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='remainder',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='remainder',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
