# Generated by Django 4.1.7 on 2023-08-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0016_alter_card_remainder_alter_historicalcard_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='total_expenses',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='total_income',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='total_expenses',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='total_income',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
