# Generated by Django 4.1.7 on 2023-08-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0017_card_total_expenses_card_total_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='total_expenses',
            new_name='total_expense',
        ),
        migrations.RenameField(
            model_name='historicalcard',
            old_name='total_expenses',
            new_name='total_expense',
        ),
    ]
