# Generated by Django 4.1.7 on 2023-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0019_balance_favourite_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='card_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='balance.card'),
        ),
    ]
