# Generated by Django 4.1.7 on 2024-01-03 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0020_alter_balance_card_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='balance.card'),
        ),
    ]
