# Generated by Django 4.1.7 on 2024-01-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('balance', '0023_remove_expenses_card_remove_income_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
