# Generated by Django 4.1.7 on 2024-01-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0026_historicalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
