# Generated by Django 4.1.7 on 2024-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0027_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='is_paid',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
