# Generated by Django 4.1.7 on 2024-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0027_currency'),
    ]

    operations = [

    ]
