# Generated by Django 4.1.7 on 2024-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0028_alter_historicalpayment_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpayment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='balance',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='balance.payment'),
        ),
    ]
