# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0030_historicalpayment_is_paid_payment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
