# Generated by Django 4.1.7 on 2024-02-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0031_card_currency_historicalcard_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='daily_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='daily_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='monthly_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='monthly_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='daily_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='daily_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='monthly_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='monthly_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
