# Generated by Django 4.1.7 on 2024-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0032_balance_daily_expense_balance_daily_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_business',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_deletable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_editable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='is_business',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='is_deletable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='is_editable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
