# Generated by Django 4.1.7 on 2024-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0033_card_is_business_card_is_deletable_card_is_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_editable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='is_editable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
