# Generated by Django 4.1.7 on 2024-03-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_expenses_child_income_child'),
        ('passives', '0045_historicalloans_is_card_loans_is_card'),
        ('balance', '0035_card_is_visible_historicalcard_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='loan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passives.loans'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='loan_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passives.loans'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.todotask'),
        ),
        migrations.AddField(
            model_name='payment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todotask'),
        ),
    ]
