# Generated by Django 4.1.7 on 2024-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0036_card_loan_link_historicalcard_loan_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='from_loan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='from_loan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
