# Generated by Django 4.1.7 on 2023-08-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepersonalcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensepersonalsubcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
