# Generated by Django 4.1.7 on 2023-08-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_expensepersonalcategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategories', models.ManyToManyField(blank=True, related_name='+', to='category.expensepersonalsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseGeneralNestedSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expensepersonalcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseGeneralSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('general_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='category.expensegeneralcategory')),
                ('nested_subcategories', models.ManyToManyField(blank=True, to='category.expensegeneralnestedsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='expensegeneralnestedsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='category.expensegeneralsubcategory'),
        ),
    ]
