# Generated by Django 4.1.7 on 2023-08-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_expensegeneralcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegeneralcategory',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='+', to='category.expensegeneralsubcategory'),
        ),
    ]
