# Generated by Django 4.1.7 on 2023-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_expensegeneralcategory_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegeneralsubcategory',
            name='general_category',
        ),
        migrations.RemoveField(
            model_name='expensegeneralsubcategory',
            name='nested_subcategories',
        ),
        migrations.RemoveField(
            model_name='expensepersonalsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expensegeneralcategory',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='expensepersonalcategory',
            name='sub_categories',
        ),
        migrations.AlterField(
            model_name='expensegeneralcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ExpenseGeneralNestedSubCategory',
        ),
        migrations.DeleteModel(
            name='ExpenseGeneralSubCategory',
        ),
        migrations.DeleteModel(
            name='ExpensePersonalSubcategory',
        ),
    ]
