# Generated by Django 4.1.7 on 2023-11-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_expensegeneralcategory_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('general_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.expensegeneralcategory')),
            ],
        ),
    ]
