# Generated by Django 4.1.7 on 2023-12-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0009_expensesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.category')),
                ('asset_type', models.CharField(choices=[('real_estate', 'Недвижимость'), ('transport', 'Транспорт'), ('business', 'Бизнес')], max_length=255)),
            ],
            bases=('category.category',),
        ),
        migrations.CreateModel(
            name='LiabilityCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.category')),
                ('liability_type', models.CharField(choices=[('real_estate', 'Недвижимость'), ('loans', 'Кредиты'), ('transport', 'Транспорт')], max_length=255)),
            ],
            bases=('category.category',),
        ),
        migrations.CreateModel(
            name='PersonalExpenseCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('category.category',),
        ),
        migrations.DeleteModel(
            name='ExpensePersonalCategory',
        ),
    ]
