# Generated by Django 4.1.7 on 2023-08-12 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_inventoryasset_text_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryasset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
