# Generated by Django 4.1.7 on 2023-08-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.inventoryexpenses'),
        ),
    ]
