# Generated by Django 4.1.7 on 2023-08-16 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0005_inventory_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('launch_status', models.BooleanField(blank=True, default=False, null=True)),
                ('total_actives_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='prev_assets', to='inventory.inventoryasset')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('expenses', models.ManyToManyField(blank=True, related_name='+', to='inventory.inventoryexpenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='previous_inventories',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_inventories', to='inventory.previousinventory'),
        ),
    ]
