# Generated by Django 4.1.7 on 2023-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_previous_inventories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.inventoryasset'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='previous_inventories',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='inventory.previousinventory'),
        ),
        migrations.AlterField(
            model_name='previousinventory',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.inventoryasset'),
        ),
    ]
