# Generated by Django 4.1.7 on 2023-08-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_alter_inventory_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInventoryAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added', models.BooleanField(blank=True, default=False, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='previousinventory',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.previousinventoryasset'),
        ),
    ]
