# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryasset_is_consumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryasset',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
