# Generated by Django 4.1.7 on 2024-02-13 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryasset_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryasset',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory'),
        ),
    ]
