# Generated by Django 4.1.7 on 2024-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryasset_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousinventoryasset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='previous_inventories',
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_consumables_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='count',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='PreviousInventory',
        ),
        migrations.DeleteModel(
            name='PreviousInventoryAsset',
        ),
    ]
