# Generated by Django 4.1.7 on 2024-02-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_previousinventoryasset_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='total_actives_cost',
        ),
    ]
