# Generated by Django 4.1.7 on 2024-02-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_inventory_total_actives_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_actives_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
