# Generated by Django 4.1.7 on 2024-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventory_total_actives_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryasset',
            name='count',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
