# Generated by Django 4.1.6 on 2023-05-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'actives_scripts',
                'verbose_name_plural': 'actives_scripts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SHORTNAME', models.TextField()),
                ('OPEN', models.FloatField()),
                ('LOW', models.FloatField()),
                ('HIGH', models.FloatField()),
                ('MARKETPRICE2', models.FloatField()),
                ('MARKETPRICE3', models.FloatField()),
            ],
            options={
                'verbose_name': 'bond',
                'verbose_name_plural': 'bonds',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('user_id', models.PositiveIntegerField()),
                ('type', models.TextField()),
                ('direction', models.TextField()),
                ('month_income', models.FloatField()),
                ('month_expense', models.FloatField()),
                ('average_profit', models.FloatField()),
                ('revenue', models.FloatField()),
                ('own_funds', models.FloatField()),
                ('third_party_tools', models.FloatField()),
                ('third_party_tools_percentage', models.FloatField()),
                ('creditor', models.TextField()),
                ('loan_sum', models.FloatField()),
                ('loan_term', models.FloatField()),
                ('percentage', models.FloatField()),
                ('month_payment', models.FloatField()),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BusinessAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('business_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'business_asset',
                'verbose_name_plural': 'business_asset',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('card_num', models.TextField(max_length=16)),
                ('card_cvc', models.TextField(max_length=3)),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'ordering': ('card_id',),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('owner', models.TextField()),
                ('rent_type', models.BooleanField()),
                ('bought_price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('initial_payment', models.FloatField()),
                ('loan_term', models.FloatField()),
                ('percentage', models.FloatField()),
                ('month_payment', models.FloatField()),
                ('revenue', models.FloatField()),
                ('equipment_price', models.FloatField()),
                ('month_income', models.FloatField()),
                ('month_expense', models.FloatField()),
                ('average_profit', models.FloatField()),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'property',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('property_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'property_asset',
                'verbose_name_plural': 'property_asset',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SHORTNAME', models.TextField()),
                ('OPEN', models.FloatField()),
                ('LOW', models.FloatField()),
                ('HIGH', models.FloatField()),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('user_id', models.PositiveIntegerField()),
                ('owner', models.TextField()),
                ('owner_type', models.TextField()),
                ('vin', models.CharField(max_length=17)),
                ('use', models.TextField()),
                ('bought_price', models.FloatField()),
                ('initial_payment', models.FloatField()),
                ('loan_term', models.FloatField()),
                ('percentage', models.FloatField()),
                ('month_payment', models.FloatField()),
                ('month_income', models.FloatField()),
                ('month_expense', models.FloatField()),
                ('average_profit', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
            options={
                'verbose_name': 'transport',
                'verbose_name_plural': 'transport',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_num', models.TextField()),
                ('cards', models.TextField()),
                ('actives', models.ManyToManyField(blank=True, to='actives.actives')),
                ('passives', models.ManyToManyField(blank=True, to='passives.passives')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='actives',
            name='businesses',
            field=models.ManyToManyField(blank=True, to='actives.business'),
        ),
        migrations.AddField(
            model_name='actives',
            name='obligation',
            field=models.ManyToManyField(blank=True, to='actives.bonds'),
        ),
        migrations.AddField(
            model_name='actives',
            name='properties',
            field=models.ManyToManyField(blank=True, to='actives.property'),
        ),
        migrations.AddField(
            model_name='actives',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='actives.stocks'),
        ),
        migrations.AddField(
            model_name='actives',
            name='transports',
            field=models.ManyToManyField(blank=True, to='actives.transport'),
        ),
    ]
