# Generated by Django 4.1.6 on 2023-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actives',
            old_name='obligation',
            new_name='bonds',
        ),
        migrations.AlterField(
            model_name='bonds',
            name='HIGH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='LOW',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='MARKETPRICE2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='MARKETPRICE3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='OPEN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='HIGH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='LOW',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='OPEN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='SHORTNAME',
            field=models.TextField(null=True),
        ),
    ]
