# Generated by Django 4.1.6 on 2023-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0002_rename_obligation_actives_bonds_alter_bonds_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='owner_type',
            field=models.BooleanField(),
        ),
    ]
