# Generated by Django 4.1.6 on 2023-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0004_alter_business_user_id_alter_card_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assets',
            field=models.ManyToManyField(blank=True, to='actives.propertyasset'),
        ),
        migrations.AlterField(
            model_name='property',
            name='actual_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bought_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='equipment_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='initial_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='loan_term',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='month_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
