# Generated by Django 4.1.6 on 2023-05-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0005_property_assets_alter_property_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='assets',
        ),
        migrations.AlterField(
            model_name='businessasset',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='actives.business'),
        ),
        migrations.AlterField(
            model_name='propertyasset',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='actives.property'),
        ),
    ]
