# Generated by Django 4.1.6 on 2023-05-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0006_remove_property_assets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessasset',
            old_name='business_id',
            new_name='business',
        ),
    ]
