# Generated by Django 4.1.6 on 2023-06-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0009_business_loan_property_loan_transport_loan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='loan_sum',
            new_name='initial_payment',
        ),
    ]
