# Generated by Django 4.1.6 on 2023-06-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0010_rename_loan_sum_business_initial_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyasset',
            old_name='property_id',
            new_name='property',
        ),
    ]
