# Generated by Django 4.1.6 on 2023-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0011_rename_property_id_propertyasset_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
