# Generated by Django 4.1.6 on 2023-06-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0012_alter_transport_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectsprofile',
            name='cards',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
