# Generated by Django 4.1.6 on 2023-06-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0013_remove_objectsprofile_cards_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessasset',
            name='done',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='done',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
