# Generated by Django 4.1.6 on 2023-07-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0014_businessasset_done_propertyasset_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='mark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='model',
            field=models.TextField(blank=True),
        ),
    ]
