# Generated by Django 4.1.6 on 2023-07-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0017_historicalbusiness_historicalbusinessasset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransport',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='brand',
        ),
    ]
