# Generated by Django 4.1.6 on 2023-07-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0019_alter_historicaltransport_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actives_transport_images/')),
                ('transport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.transport')),
            ],
            options={
                'verbose_name': 'transport-image',
                'verbose_name_plural': 'transport-image',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.business')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.property')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.business')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.property')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.transport')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='actives.transportimage'),
        ),
    ]
