# Generated by Django 4.1.6 on 2023-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0020_business_total_expense_business_total_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actives',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalbusiness',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalproperty',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicaltransport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='objectsprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='actives',
            name='total_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actives',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
