# Generated by Django 4.1.6 on 2023-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0021_rename_user_id_actives_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.transportimage'),
        ),
    ]
