# Generated by Django 4.1.6 on 2023-07-31 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0023_remove_actives_bonds_remove_actives_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.expenses'),
        ),
        migrations.AddField(
            model_name='business',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.income'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.expenses'),
        ),
        migrations.AddField(
            model_name='property',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.income'),
        ),
        migrations.AddField(
            model_name='transport',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.expenses'),
        ),
        migrations.AddField(
            model_name='transport',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.income'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.business'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.property'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.transport'),
        ),
        migrations.AlterField(
            model_name='income',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.business'),
        ),
        migrations.AlterField(
            model_name='income',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.property'),
        ),
        migrations.AlterField(
            model_name='income',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actives.transport'),
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'securities',
                'verbose_name_plural': 'securities',
                'ordering': ('id',),
            },
        ),
    ]
