# Generated by Django 4.1.6 on 2023-07-31 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0020_rename_user_id_historicalloans_user_and_more'),
        ('actives', '0024_business_expenses_business_income_expenses_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='loan_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passives.loans'),
        ),
        migrations.AddField(
            model_name='property',
            name='loan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='passives.loans'),
        ),
    ]
