# Generated by Django 4.1.6 on 2023-07-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0026_business_loan_link_historicalbusiness_loan_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='name',
        ),
    ]
