# Generated by Django 4.1.7 on 2023-08-07 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0027_remove_historicaltransport_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actives',
            name='businesses',
        ),
        migrations.RemoveField(
            model_name='actives',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='actives',
            name='transports',
        ),
        migrations.CreateModel(
            name='MainTransport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, null=True)),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('total_expenses', models.FloatField(blank=True, null=True)),
                ('transport', models.ManyToManyField(blank=True, to='actives.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainProperties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, null=True)),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('total_expenses', models.FloatField(blank=True, null=True)),
                ('properties', models.ManyToManyField(blank=True, to='actives.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainBusinesses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, null=True)),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('total_expenses', models.FloatField(blank=True, null=True)),
                ('businesses', models.ManyToManyField(blank=True, to='actives.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actives',
            name='businesses',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.mainbusinesses'),
        ),
        migrations.AddField(
            model_name='actives',
            name='properties',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.mainproperties'),
        ),
        migrations.AddField(
            model_name='actives',
            name='transports',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.maintransport'),
        ),
    ]
