# Generated by Django 4.1.7 on 2023-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0029_alter_actives_businesses_alter_actives_properties_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actives',
            options={'ordering': ('id',), 'verbose_name': 'actives', 'verbose_name_plural': 'actives'},
        ),
        migrations.AlterField(
            model_name='mainbusinesses',
            name='businesses',
            field=models.ManyToManyField(blank=True, null=True, to='actives.business'),
        ),
        migrations.AlterField(
            model_name='mainproperties',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, to='actives.property'),
        ),
        migrations.AlterField(
            model_name='maintransport',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, to='actives.transport'),
        ),
    ]
