# Generated by Django 4.1.7 on 2023-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0031_alter_actives_businesses_alter_actives_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actives',
            name='total_funds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
