# Generated by Django 4.1.7 on 2023-08-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0027_alter_passives_loans_alter_passives_properties_and_more'),
        ('actives', '0032_actives_total_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='loan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_loan_link', to='passives.loans'),
        ),
    ]
