# Generated by Django 4.1.7 on 2023-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0034_alter_actives_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bought_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='bought_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
