# Generated by Django 4.1.7 on 2023-08-12 02:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0037_business_equipment_historicalbusiness_equipment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income',
            new_name='ActivesExpenses',
        ),
        migrations.RenameModel(
            old_name='Expenses',
            new_name='ActivesIncome',
        ),
    ]
