# Generated by Django 4.1.7 on 2023-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0038_rename_income_activesexpenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesexpenses'),
        ),
        migrations.AlterField(
            model_name='business',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesincome'),
        ),
        migrations.AlterField(
            model_name='property',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesexpenses'),
        ),
        migrations.AlterField(
            model_name='property',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesincome'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesexpenses'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesincome'),
        ),
    ]
