# Generated by Django 4.1.7 on 2023-08-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0013_expenses_category'),
        ('actives', '0040_activesexpenses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesexpenses',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.card'),
        ),
    ]
