# Generated by Django 4.1.7 on 2023-08-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0041_activesexpenses_writeoff_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesexpenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activesexpenses',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activesexpenses',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
