# Generated by Django 4.1.7 on 2023-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0045_alter_business_loan_link_alter_property_loan_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='creditor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='creditor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
