# Generated by Django 4.1.7 on 2023-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0047_alter_business_own_funds'),
    ]

    operations = [

    ]
