# Generated by Django 4.1.7 on 2023-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0048_alter_business_own_funds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='own_funds',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness',
            name='own_funds',
        ),
    ]
