# Generated by Django 4.1.7 on 2023-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0049_remove_business_own_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='own_funds',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='own_funds',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
