# Generated by Django 4.1.7 on 2023-12-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0020_alter_balance_card_list'),
        ('actives', '0050_business_own_funds_historicalbusiness_own_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesincome',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activesincome',
            name='writeoff_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.card'),
        ),
        migrations.AddField(
            model_name='business',
            name='own_funds_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='own_funds_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
