# Generated by Django 4.1.7 on 2024-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0052_remove_historicalproperty_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproperty',
            name='building_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
