# Generated by Django 4.1.7 on 2024-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0053_alter_historicalproperty_building_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesexpenses',
            name='category',
        ),
    ]
