# Generated by Django 4.1.7 on 2024-02-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0056_securities_jewelry_historicalsecurities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='total_worth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='total_worth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='MainSecurities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, default=0.0, null=True)),
                ('securities', models.ManyToManyField(blank=True, null=True, to='actives.securities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainJewelry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, default=0.0, null=True)),
                ('jewelries', models.ManyToManyField(blank=True, null=True, to='actives.jewelry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actives',
            name='jewelries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.mainjewelry'),
        ),
        migrations.AddField(
            model_name='actives',
            name='securities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.mainsecurities'),
        ),
    ]
