# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0057_business_total_worth_historicalbusiness_total_worth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDeposits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainLoans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_funds', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
