# Generated by Django 4.1.7 on 2024-02-12 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0058_maindeposits_mainloans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainloans',
            name='loans',
            field=models.ManyToManyField(blank=True, null=True, to='actives_deposit.activesloans'),
        ),
        migrations.AddField(
            model_name='mainloans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maindeposits',
            name='deposits',
            field=models.ManyToManyField(blank=True, null=True, to='actives_deposit.activesdeposit'),
        ),
        migrations.AddField(
            model_name='maindeposits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actives',
            name='deposits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.maindeposits'),
        ),
        migrations.AddField(
            model_name='actives',
            name='loans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actives.mainloans'),
        ),
    ]
