# Generated by Django 4.1.7 on 2024-02-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0059_mainloans_loans_mainloans_user_maindeposits_deposits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='rent_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_type',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='rent_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
