# Generated by Django 4.1.7 on 2024-02-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0033_card_is_business_card_is_deletable_card_is_editable_and_more'),
        ('actives', '0061_historicalproperty_rent_type_property_rent_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransport',
            old_name='owner',
            new_name='owner_count',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='owner',
            new_name='owner_count',
        ),
        migrations.RemoveField(
            model_name='actives',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='historicaltransport',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='vin',
        ),
        migrations.AddField(
            model_name='business',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='balance.card'),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='card',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='balance.card'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MainLoans',
        ),
    ]
