# Generated by Django 4.1.7 on 2024-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0062_rename_owner_historicaltransport_owner_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljewelry',
            name='total_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicaljewelry',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalsecurities',
            name='total_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalsecurities',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesexpenses'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesincome'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='total_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='securities',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesexpenses'),
        ),
        migrations.AddField(
            model_name='securities',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='+', to='actives.activesincome'),
        ),
        migrations.AddField(
            model_name='securities',
            name='total_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='securities',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
