# Generated by Django 4.1.7 on 2024-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0063_historicaljewelry_total_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindeposits',
            name='total_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='maindeposits',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='mainjewelry',
            name='total_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='mainjewelry',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='mainsecurities',
            name='total_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='mainsecurities',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
