# Generated by Django 4.1.7 on 2024-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0064_maindeposits_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecurities',
            name='sum',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='securities',
            name='sum',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
