# Generated by Django 4.1.7 on 2024-03-27 14:36

from django.db import migrations, models
import test_backend.custom_methods


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0065_historicalsecurities_sum_securities_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=test_backend.custom_methods.RandomFileName('actives_transport_images/')),
        ),
    ]
